[[redirects]]
  # redirects /feed to feed.xml RSS file
  from = "/feed"
  to = "/feed.xml"
  force = true

[[headers]]
  # sets headers for font files
  for = '/assets/fonts/*'
  [headers.values]
    cache-control = 'public, max-age=18144000' # One month
  # sets headers for scripts
  for = '/assets/fonts/*'
  [headers.values]
    cache-control = 'public, max-age=604800' # One week