# redirects /feed to feed.xml RSS file
[[redirects]]
  from = "/feed"
  to = "/feed.xml"
  force = true

# sets headers for font delivery
[[headers]]
  for = '/assets/fonts/*'
  [headers.values]
    cache-control = 'public, max-age=31536000'